### ISSUE TITLE
 how to setUserid from user?? 

### ISSUE THREAD

**Issue by ramHruday** [Amsterdam/matomo-tracker#106]
I need to set User on logging in, how can't achieve that..
Any examples

**Comment by chrisvanmook** [comment]
@ramHruday I'm not sure what you want to do... Could you explain in detail / give an example what do you want to accomplish?

**Comment by ramaHruday** [comment]
_paq.push(['setUserId', 'USER_ID_HERE']);
_paq.push(['trackPageView']);

thanks for immediate response

**Comment by chrisvanmook** [comment]
@ramaHruday Unfortunately it's still too insufficient info... Which package are you using (react or js?) I strongly suggest you take a look at the documentation on how to track events and page views, as we use different methods to call them (unlike your example with `_paq`): 
- js: https://github.com/Amsterdam/matomo-tracker/tree/master/packages/js
- react: https://github.com/Amsterdam/matomo-tracker/tree/master/packages/react

Hope this helps

**Comment by chrisvanmook** [comment]
@ramaHruday Is this issue still relevant? Otherwise will close it.

**Comment by chriggi** [comment]
Can this be reopened? I'm looking for this too. More info can be found on matomo's homepage: https://developer.matomo.org/guides/tracking-javascript-guide#user-id

**Comment by chrisvanmook** [comment]
@chriggi @ramaHruday This is fixed in version [v0.1.5](https://github.com/Amsterdam/matomo-tracker/releases/tag/v0.1.5)

**Comment by chriggi** [comment]
@chrisvanmook unfortunately it's not fixed yet. While you can set a userId on initialization, I can't set it programmatically (via `_paq.push(['setUserId', 'USER_ID_HERE']);`, see my link above). I don't have the userId yet on initialization as it is stored in the redux store, and it might only be available after login. 
Ideally we could have a function similar to `trackPageView` named `setUserId` which sets the userId **after** initialization.
Thanks

**Comment by chrisvanmook** [comment]
@chriggi thanks for the clear explanation. I think this is something to take into account when working on issue #176

**Comment by CoenWarmer** [comment]
This would be very nice to have :)

**Comment by jonkoops** [comment]
This should now be possible on `master` by calling [pushInstruction](https://github.com/Amsterdam/matomo-tracker/blob/master/packages/js/src/MatomoTracker.ts#L333) as follows:

```ts
const tracker = new MatomoTracker({ ... })

tracker.pushInstruction('setUserId', 'USER_ID_HERE')
```

**Comment by lgp171188** [comment]
@jonkoops, since the fix for this issue is on the `master` branch and not in a tagged release, can you create a new tagged release so that it is possible to make use of this feature?

**Comment by jonkoops** [comment]
@lgp171188 We just released `v0.2.0` which includes this change.

**Comment by lgp171188** [comment]
@jonkoops, this is great news! Thanks for acting and responding very quickly! 👍🏼

**Comment by lgp171188** [comment]
(this issue is probably not the right place to ask this question, but can't find a better place)

@jonkoops, the [usage instructions](https://github.com/Amsterdam/matomo-tracker/issues/106#issuecomment-668117853) that you have shared are not clear about how one could use the `pushInstruction` method from a React component. For instance the `useMatomo` doesn't return the `pushInstruction` method of the `instance` [here](https://github.com/Amsterdam/matomo-tracker/blob/master/packages/react/src/useMatomo.ts#L31). Should one create an instance manually by

```javascript
const instance = React.useContext(MatomoContext);
```
?

If yes, I'd like to submit a documentation PR mentioning this. If not, would it be okay to expose the  `pushInstruction` method in via the `useMatomo` function? I can submit a PR for that as well.

**Comment by jonkoops** [comment]
@lgp171188 Yeah, I am not happy with how the React context works here. We're thinking about changing this API in the future.

I've created https://github.com/Amsterdam/matomo-tracker/pull/242 to export the method in the `useMatomo` hook as well. If you want to open up a PR for documentation that is of course always welcome :+1:

**Comment by lgp171188** [comment]
@jonkoops, thanks for the very quick response and creating+merging #242. I have created a documentation PR https://github.com/Amsterdam/matomo-tracker/pull/243 mentioning the functions exposed by the `useMatomo()` hook and also an example for using the `pushInstructions()` function. 👍🏼 

Since this is a monorepo with both the JS and React versions of the library, there is no easy way to install the master branch and hence it will be great if you can tag a new release once all the changes planned for that release are merged and ready. Thanks again! 🙂

**Comment by jonkoops** [comment]
Thanks @lgp171188, it's much appreciated. If you want to use that package locally I would recommend building the project locally, buidling it and use `yarn link` or `npm link` to link the package to your project.

Regardless of this we will publish a new version that includes this fix soon.
